#ifndef TOKEN_TYPE_H
#define TOKEN_TYPE_H

typedef enum {
    FLOAT, EXPFLOAT, DECINTEGER, HEXINTEGER, STRING, COMMENT,
    RESERVED, OPERATOR, DELIMITER, IDENT, UNKNOWN
} TokenType;

#endif // TOKEN_TYPE_H